spring:
  application:
    name: clients

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user-course:eru-reuesrkeauo-sc@${EUREKA_SERVER}:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/logs-file.log